name: mysql
version: 0.3.7
appVersion: 5.7.14
description: Fast, reliable, scalable, and easy to use open-source relational database
  system.
keywords:
- mysql
- database
- sql
home: https://www.mysql.com/
icon: file://../logo.png
sources:
- https://github.com/kubernetes/charts
- https://github.com/docker-library/mysql
maintainers:
- name: Vic Iglesias
  email: viglesias@google.com
engine: gotpl
