kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "f5-vs-config.fullname" . }}
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": {{ .Values.servicePort }},
          "serviceName": "{{ .Values.serviceName }}"
        },
        "frontend": {
          "virtualAddress": {
            "port": {{ .Values.virtualAddress.port }},
            "bindAddr": "{{ .Values.virtualAddress.bindAddr }}"
          },
          "partition": "{{ .Values.partition }}",
          "balance": "{{ .Values.balance }}",
          "mode": "{{ .Values.mode }}"
        }
      }
    }
