kind: ConfigMap
apiVersion: v1
metadata:
  name: iapp-{{ .Values.iappVariables.protocol }}-vs-{{ .Values.iappVariables.pool__addr }}-{{ .Values.iappVariables.pool__port }}
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
   {
     "virtualServer": {
       "backend": {
         "serviceName": "{{ .Values.serviceName }}",
         "servicePort": {{ .Values.servicePort }}
       },
       "frontend": {
         "partition": "{{ .Values.partition }}",
         "iapp": "{{ .Values.iapp }}",
         "iappPoolMemberTable": {
           "name": "pool__members",
           "columns": [
               {"name": "addr", "kind": "IPAddress"},
               {"name": "port", "kind": "Port"},
               {"name": "connection_limit", "value": "0"}
           ]
         },
         "iappOptions": {
           "description": "{{ .Values.iappOptions.description }}"
         },
         "iappVariables": {
           "pool__pool_to_use": "{{ .Values.iappVariables.pool__pool_to_use }}",
           "pool__addr": "{{ .Values.iappVariables.pool__addr }}",
           "pool__port": "{{ .Values.iappVariables.pool__port }}",
           "vs__SNATConfig": "{{ .Values.iappVariables.vs__SNATConfig }}",
           "vs__ProfileDefaultPersist": "{{ .Values.iappVariables.vs__ProfileDefaultPersist }}",
           "pool_lb": "{{ .Values.iappVariables.pool_lb }}",
           {{- if .Values.iappVariables.protocol=tcp }}
           "monitor__Monitors": "tcp_new send 'udpdata' recv 'nginx' interval 10 timeout 31",
           "pool__irules": "when CLIENT_ACCEPTED { \r\n log local0. \"clientIP[IP::client_addr]\"\r\n} "
           {{- end }}
         }
       }
     }
   }
